server:
    port: 8080

management:
    endpoints:
        web:
            exposure:
                include: health,info,loggers,metrics
    endpoint:
        health:
            show-details: always
    health:
        diskSpace:
            enabled: false
    info:
        git:
            mode: full

spring:
    datasource:
        url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5490}/db
        username: user
        password: sldmsdiwoeu867
    jpa:
        show-sql: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                hbm2ddl:
                    auto: create-drop
    graphql:
        path: /graphql
        graphiql:
            enabled: true

logging:
    level:
        root: DEBUG
        com.graphql_java_generator: DEBUG
        org.zalando.logbook: TRACE

de:
    adesso:
        lasttest:
            jwtSecret: ====================================BezKoder=Spring========================================
            jwtExpirationMs: 30000
            jwtRefreshExpirationMs: 86400000 # 24h